# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 00:01
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposition',
            fields=[
                ('title', models.CharField(max_length=120)),
                ('content', models.CharField(max_length=5120)),
                ('slug', autoslug.fields.AutoSlugField(editable=True, max_length=120, populate_from='title', primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('NEW', 'nouvelle proposition'), ('REMOVED', 'proposition supprimée'), ('LOCKED', 'proposition verrouillée'), ('EXPIRED', 'proposition expirée'), ('VOTING', 'proposition soumise au vote'), ('ACCEPTED', 'proposition adoptée'), ('DENIED', 'proposition retoquée')], default='NEW', max_length=24)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
