# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 00:30
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proposition',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=120, populate_from='title', unique=True),
        ),
    ]
