# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 01:11
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propositions', '0002_auto_20160321_0130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='id',
        ),
        migrations.AlterField(
            model_name='proposition',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=True, max_length=120, populate_from='title', primary_key=True, serialize=False, unique=True),
        ),
    ]
